config/routes.rb
BlogApp::Application.routes.draw do
  root :to => "posts#index"

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "index" => "posts#index", :as => "index"

  get  "sign_up" => "users#new", :as =>"sign_up"
  
  resources :users
  resources :sessions
  resources :posts do
    resources :comments
end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	validates_presence_of :post_id
	validates_presence_of :body
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates_presence_of :title
	validates_presence_of :body
end

app/models/user.rb
class User < ActiveRecord::Base
	/attr_accessible :email, :password, :password_confirmation/
	attr_accessor :password
	before_save :encrypt_password

	validates_confirmation_of :password
	validates_presence_of :password, :on => :create
	validates_presence_of :email
	validates_uniqueness_of :email
	validates_length_of :password, :in => 6..15


	def self.authenticate(email,password)
		user = find_by_email(email)
		if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
			user
		else
			nil
		end
	end

	def encrypt_password
		if password.present?
			self.password_salt = BCrypt::Engine.generate_salt
			self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :have_email  

  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def have_email
  	if @current_user.email = "nit0099@gmail.com"
  		return true
  	else
  		return false
  	end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @comment }
        format.js # create.js.erb if nothing is given.
      else
        format.html { render action: 'new' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:post_id, :body)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate, except: [:index,:show]
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: 'Post was successfully created.' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end

    def authenticate
      authenticate_or_request_with_http_basic do |name,password|
        name == "admin" && password == "secret"
      end
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:email], params[:password])
  	if user
  		session[:user_id] = user.id
  		redirect_to root_url, :notice => "Logged In!"
  	else
  		flash.now.alert = "Invalid email or password"
  		render "new"
    end 
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, :notice => "Signed Up"
		else
			render "new"
		end
	end

  	private

  	def user_params
    	params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
  	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<%= div_for comment do %>
	<p>
		<strong> Posted <%= time_ago_in_words(comment.created_at) %></strong><br />
		<%= h(comment.body) %>
	</p>
<% end %>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %><br>
    <%= f.number_field :post_id %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
var new_comment = $("<%= escape_javascript(render(:partial => @comment))%>").hide();
$('#comments').prepend(new_comment);
$('#comment_<%= @comment.id %>').fadeIn('slow');
$('#new_comment')[0].reset();

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Listing comments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.post_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @comment.post_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ragingsin Blog -- Code is Everywhere.</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

<!--
<div id="navbar">
	<% if current_user %>
		Logged in as <%= current_user.email %>.
		<%= link_to "Log out", log_out_path %>
	<% else %>
	<%= link_to "Sign Up" , sign_up_path %> or
	<%= link_to "log in", log_in_path %>
	<% end %>
</div>

-->

<div class="navbar navbar-fixed-top nav-justified">
<div class="navbar-inner">
  <div class="container-fluid">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <a class="brand" href="./">RagingSin</a>
    <div class="nav-collapse">
      <ul class="nav">
      	<% if current_user %>
      	<li>
      		Logged in as <%= current_user.email %> 
          <%= link_to "Log_out", log_out_path %></li>
      	<% else %>
        <li><%= link_to "SignUp", sign_up_path %></li>
       	<li><%= link_to "Login", log_in_path %></li>
       	<% end %>
      </ul>
    </div>
  </div>
</div>
</div>


<div class="container-fluid">
  <div class="row-fluid">
    <div class="span warning">
      <%= flash.each do |name, msg| %>
	     <% content_tag :div, msg, :id => "flash_#{name}" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container-fluid">
  <div class="row-fluid">
    <div class="span9">
      <%= yield %>
    </div>
    <div class="span2">
      <h2>About Me</h2>
        Hey, My name is Nitish Singh and welcome to my blog page. I created this Blog Site to fulfill the purose of mini-project for my B level. The Blog is build using Rails 4. Encyrption Library BCrypt is used to encrypt user information in the database. SQLlite as the server side technology. In Frontend Twitter Bootstrap is used make the site look beautiful. AJAX is used to dynamically add comments under blog posts. This is a beautiful example of Rails 4 and it's MVC architecture.
        <br />
        <h3> Archives </h3>
        <div id="archive"><% link_to "post.title" %> </div
    </div>
  </div>
</div>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<!--

<h1 id="title">RagingSin</h1>
<h2 id="subtitle">Code is Everywhere</h1>
<h2> Login </h2>
<h2> SignUp </h2>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
-->
<br>

<div class="page-header">
  <h1>RagingSin <small>   Code is Everywhere</small></h1>
</div>


<div class="container-fluid">
  <% @posts.each do |post| %>
  <div id = "post_title" ><%= post.title %></div>
  <div id = "post_body"><%= post.body %> </div>
  <% if current_user && current_user.email = "nit0099@gmail.com" %>
  <div id = "read_more"><%= link_to 'Read More', post %> </div>
  <div id = "edit_post"><%= link_to 'Edit', edit_post_path(post) %></div>
  <% else %>
  <div id = "read_more"><%= link_to 'Read More', post %> </div>
  <% end %>
  <% end %>
</div>

<br />
<div id="container-fluid">
  <div id="row-fluid">
    <% if current_user && (current_user.email = "ni0099@gmail.com" || current_user.email ="prerna@gmail.com") %>
      <div class="container"><%= link_to 'New Post', new_post_path %></div>
    <% else %>
      <%= nil %>
    <% end %>
</div>
</div>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong> <%= @post.title %></strong>
</p>

<p>
  <strong></strong>
  <%= @post.body %>
</p>


<h2> Comments </h2>
<div id ="comments">
	<%= render :partial => @post.comments.reverse %>
</div>

<%= form_for([@post,Comment.new], remote: true) do |f| %>
	<p><%= f.label :body, "New Comment" %><br />
		<%= f.text_area :body %>
	</p>
	<p><%= f.submit "Add Comment" %></p>
<% end %>

<% if current_user && current_user.email = "nit0099@gmail.com" %>
	<%= link_to 'Edit', edit_post_path(@post) %>
	<%= link_to 'Back', posts_path %>
	<% else %>
		<%= link_to 'Back', posts_path %>
<% end %>

app/views/users/new.html.erb
<h1 id="title">Sign Up</h1>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_message">
			<h2> Form is invalid</h2>
			<ul>
				<% for message in @user.errors.full_messages %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :email %> <br />
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :password %> <br />
		<%= f.password_field :password %>
	</p>

	<p>
		<%= f.label :password_confirmation %> <br />
		<%= f.password_field :password_confirmation %>
	</p>

	<p class = "button"> <%= f.submit %> </p>

<% end %>